version: "3.8"

networks:
  sail:
    # driver: bridge

volumes:
  sail-mysql:
    # driver: local
  sail-redis:
    driver: local

services:
  backend:
    build: ./backend/
    env_file: ./backend/.env
    volumes:
      - "./backend:/app"
    ports:
      - "${SERVICE_BACKEND_PORT:-8000}:8000"
    networks:
      - sail
    depends_on:
      - mysql
    extra_hosts:
      - host.docker.internal:host-gateway

  mysql:
    build: ./mysql
    env_file: ./mysql/.env
    ports:
      - "${SERVICE_MYSQL_PORT:-3306}:3306"
    networks:
      - sail

  phpmyadmin:
    build: ./phpmyadmin
    env_file: ./phpmyadmin/.env
    ports:
      - "${SERVICE_PMA_PORT:-8081}:80"
    networks:
      - sail
    depends_on:
      - mysql

  keycloak:
    build: ./keycloak
    env_file: ./keycloak/.env
    command: start-dev
    ports:
      - ${SERVICE_KEYCLOAK_PORT:-8002}:8080
    networks:
      - sail
    # volumes:
    #   - "./keycloak/db:/opt/keycloak/data"

  # frontend:
  #   build: ./.docker/frontend
  #   env_file: ./frontend/.env
  #   command: bash -c "yarn install && yarn dev"
  #   ports:
  #     - ${VITE_PORT:-24678}:${VITE_PORT:-24678}
  #     - ${FRONTEND_PORT:-3000}:3000
  #   volumes:
  #     - "./frontend:/app"
  #   networks:
  #     - sail

  # websocket:
  #   build: ./.docker/websocket
  #   env_file: ./websocket/.env
  #   command: bash -c "yarn install && yarn dev"
  #   ports:
  #     - ${WEBSOCKET_PORT:-8443}:80
  #   volumes:
  #     - "./websocket:/app"
  #   networks:
  #     - sail
